
name: release

on:
  # Run this from the Action tab
  workflow_dispatch:
  # Otherwise trigger when a tag is pushed
  push:
    tags: [ "*" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Prepare release
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        echo "$(basename "$GITHUB_REF_NAME")"
        printf "#define VERSION \"%s\"\\n" "$(basename "$GITHUB_REF_NAME")" > version.h
    - name: Compile
      run: |
        make default
    - name: Upload zip to release
      if: startsWith(github.ref, 'refs/tags/')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: netrelay
        tag: ${{ github.ref }}
        overwrite: true

