
name: release

on:
  # Run this from the Action tab
  workflow_dispatch:
  #~ # Otherwise trigger when a tag is pushed
  #~ push:
    #~ tags: [ "*" ]
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Prepare
      run: |
        incdir=/usr/include/x86_64-linux-musl
        sudo apt-get remove --purge man-db
        sudo apt-get update && sudo apt-get install -y musl-tools musl-dev
        ( cd "$incdir" && sudo cp -rs /usr/include/linux linux )
    - name: Compile
      run: |
        make default CC=musl-gcc "DVERSION=-DVERSION='\"$(basename "${GITHUB_REF_NAME}")\"'"
    - name: Upload to release
      if: startsWith(github.ref, 'refs/tags/')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: netrelay
        tag: ${{ github.ref }}
        overwrite: true

