
name: release

on:
  # Run this from the Action tab
  workflow_dispatch:
  #~ # Otherwise trigger when a tag is pushed
  #~ push:
    #~ tags: [ "*" ]
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    #~ - name: Cache pkgs
      #~ id: cache-pkgs
      #~ uses: actions/cache@v4
      #~ with:
        #~ path: /var/cache/apt/archives
        #~ key: ${{ runner.os }}-pkgs
    #~ - name: Install packages
      #~ run: |
        #~ sudo apt-get remove --purge man-db
        #~ sudo apt-get update
        #~ sudo apt-get install -y musl-tools musl-dev linux-libc-dev
    - name: Disable man-db
      run: |
        sudo apt-get remove --purge man-db
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: musl-tools musl-dev linux-libc-dev
        version: 1.0
    - name: Prepare things for musl uploads
      run: |
        set -x
        mkdir -p compat
        ln -sf /usr/include/$(arch)-linux-gnu/asm compat/asm
        ln -sf /usr/include/asm-generic compat/asm-generic
        ln -sf /usr/include/linux compat/linux
    - name: Compile MUSL version
      run: |
        make default CC=musl-gcc "DVERSION=-Icompat -DVERSION='\"$(basename "${GITHUB_REF_NAME}")\"'"
        zip "netrelay-$(basename "${GITHUB_REF_NAME}")-musl.$(arch).bin.zip" netrelay
    - name: Do NOT release, just create artifact.
      uses: actions/upload-artifact@v4
      with:
        path: netrelay-*.zip
    - name: Upload to release
      if: startsWith(github.ref, 'refs/tags/')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: netrelay-*.zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true


