
name: release

on:
  # Run this from the Action tab
  workflow_dispatch:
  #~ # Otherwise trigger when a tag is pushed
  #~ push:
    #~ tags: [ "*" ]
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache pkgs
      id: cache-pkgs
      uses: actions/cache@v4
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-pkgs
    - name: Install packages
      run: |
        sudo apt-get remove --purge man-db
        sudo apt-get update && sudo apt-get install -y musl-tools musl-dev
    - name: Prepare
      run: |
        incdir=/usr/include/x86_64-linux-musl
        arch=x86
        set -x
        sudo cp -rs /usr/include/linux "$incdir/linux"
        sudo cp -rs /usr/src/linux-headers-$(uname -r)/arch/$arch/include/generated/uapi/asm "$incdir/asm"
        :
        find $(find /usr/include /usr/src -type d -name asm-generic) -name types.h
        sudo mkdir -p $incdir/asm-generic
        sudo cp -rs /usr/src/linux-*-headers-*/include-asm-generic/*  /usr/include/asm-generic/* "$incdir/asm-generic"
        #~ find /usr/include /usr/src -name bitsperlong.h
        #~ find /usr/include /usr/src -type d -name asm
        #~ find /usr/src/linux-headers-$(uname -r) -name types.h
        #~ ls -ld /usr/src/linux-headers-$(uname -r)/ || :
        #~ ls -ld /usr/src/linux-headers-$(uname -r)/arch || :
        #~ ls -ld /usr/src/linux-headers-$(uname -r)/arch/$arch || :
        #~ ls -ld /usr/src/linux-headers-$(uname -r)/arch/$arch/include || :
        #~ ls -ld /usr/src/linux-headers-$(uname -r)/arch/$arch/include/asm || :
        #~ ls /usr/src/linux-headers-$(uname -r)/ || :
        #~ ls /usr/src/linux-headers-$(uname -r)/arch || :
        #~ ls /usr/src/linux-headers-$(uname -r)/arch/$arch|| :
        #~ ls /usr/src/linux-headers-$(uname -r)/arch/$arch/include || :
        #~ ls /usr/src/linux-headers-$(uname -r)/arch/$arch/include/asm || :

        #~ ls -l /usr/include
        #~ ls -l /usr/include/asm || :
        #~ ls -l /usr/src || :
        #~ ls -ld /usr/src/*/arch || :
        #~ uname -r
        #~ find /usr/src/*/arch -name asm || :

        #~ ( cd "$incdir" && sudo cp -rs /usr/include/asm asm )
        #~ ( cd "$incdir" && sudo cp -rs /usr/include/asm-generic asm-generic )
    - name: Compile
      run: |
        make default CC=musl-gcc "DVERSION=-DVERSION='\"$(basename "${GITHUB_REF_NAME}")\"'"
    - name: Upload to release
      if: startsWith(github.ref, 'refs/tags/')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: netrelay
        tag: ${{ github.ref }}
        overwrite: true

